##### kullanılan paketler #####
packages <- c("Rcpp", "zip", "readr", "tidyverse", "readxl", "magrittr", "ggplot2", "gridExtra", "stringr", "car", "openxlsx", "jsonlite",
              "scales", "caret", "lattice", "MASS", "dplyr", "forecast", "this.path", "Metrics", "boot", "glmnet", "zoo", "elasticnet", "timeDate")

# paketler yüklü değilse yükle, yüklüyse içeri aktar
for (i in 1:length(packages)) {
  if(packages[i] %in% rownames(installed.packages())){
    library(packages[i], character.only = TRUE)
  } else {
    print(paste0("Paket ismi: ", packages[i], " yukleniyor..."))
    install.packages(packages[i], repos = "http://cran.us.r-project.org", dependencies = TRUE)
    library(packages[i], character.only = TRUE)
    print(paste0("Paket yuklendi!"))
  }
}

# encoding'i Türkçe'ye ayarlar
Sys.setlocale("LC_CTYPE", "tr_TR.UTF-8")


# CLI deki argumentlerin tutulacağı objenin oluşturulması
args <- commandArgs(trailingOnly = TRUE)


##### Config dosyasını oku #####
config <- jsonlite::fromJSON(args[1]) 


user_root_path <- Sys.getenv("USERPROFILE")

# çalışma klasörünü current klasöre ayarla
setwd(this.dir())

# Path to the input Excel file generated by the first script
excel_input_file_path <- paste0(user_root_path,"/",
                                config$Ana_Klasör_Yolu, "/",
                                config$İl, "/",
                                config$İlçe, "/",
                                config$ELF$SONUÇLAR_klasör, "/",
                                config$ELF$SONUÇLAR_name)

# Read the specified sheet from the input Excel file based on args[2]
sheet_index <- as.numeric(args[2])


if (!(sheet_index %in% 1:5)) {
  stop("Sheet index must be between 1 and 5")
}

# Map sheet index to sheet name
sheet_names <- c("Bagımlı_Degisken_Tahminleri_1", "Bagımlı_Degisken_Tahminleri_2", 
                 "Bagımlı_Degisken_Tahminleri_3", "Bagımlı_Degisken_Tahminleri_4", 
                 "Bagımlı_Degisken_Tahminleri_5")

# Read data from the specified sheet
original_data <- read_excel(excel_input_file_path,
                            sheet = sheet_names[sheet_index],
                            col_names = TRUE,
                            col_types = rep("numeric", 21)) %>%
  as.data.frame()



excel_input_file_path <- paste0(user_root_path,"/",
                                config$Ana_Klasör_Yolu, "/",
                                config$İl, "/",
                                config$İlçe, "/",
                                config$ELF$INPUT_FILE)

##### Ana girdi dosyasını yükle #####
d <- read_excel(excel_input_file_path,
                sheet = 1,
                col_names = TRUE,
                col_types = rep("numeric", 43)) %>%
  as.data.frame()



#   --------------------------------------------  #
# function to extract only the filled cells from the original data
filled_cells <- function(d, t){
  
  d_filled <- d[which(is.na(d[,t]) == FALSE), t]
  return(d_filled)
}

# function to do the necessary data pre-processing
data_preparation <- function(d){
  d <- as.data.frame(d)
  d %>%
    rename("faturalanan" = 1) %>%
    mutate(faturalanan = as.numeric(faturalanan)) -> d
}

# training set length for consumption values
nrow_dataset_tuketim <- data_preparation(filled_cells(d, 7)) %>% nrow()
last_known_year_nufus <- max(d$YIL[!is.na(d$ILCE_NUFUS)]) # Last year with known population data

# the index of the last nufus/faturalanan data
last_known_year_nufus_index <- which(d$YIL == last_known_year_nufus)

# Horizon years
h <- config$ELF$ufuk_yılı

# Extract years from the data
years <- d$YIL[(last_known_year_nufus_index-2):(last_known_year_nufus_index+h+1)]
n_rows <- length(years)


original_data <- original_data[(last_known_year_nufus_index-2):(last_known_year_nufus_index + h + 1),]


# Function to create and populate the new Excel file for the specified sheet index
create_vertical_analysis_file <- function(sheet_index) {
  
  # Map sheet index to output sheet name
  output_sheet_names <- c("Minimum", "Dusuk", "Baz", "Yuksek", "Maksimum")
  output_sheet_name <- output_sheet_names[sheet_index]
  
  # Create a new workbook
  vertical_workbook <- createWorkbook()
  
  # Add a single sheet to the new workbook
  addWorksheet(vertical_workbook, output_sheet_name)
  
  # Create style for formatting
  my_style <- createStyle(fontName = "Calibri",
                          fontSize = 11,
                          valign = "center",
                          halign = "center",
                          numFmt = "#,##0")
  
  print("Yatay ve dikey büyüme rakamları oluşturuluyor....")
  
  # Initialize the data frame with the required columns
  vertical_data <- data.frame(
    ILCE = rep(1, n_rows),
    YIL = years,
    MESKEN_FATURALANAN = original_data$MESKEN_FATURALANAN,
    SANAYI_FATURALANAN = original_data$SANAYI_FATURALANAN,
    TICARETHANE_FATURALANAN = original_data$TICARETHANE_FATURALANAN,
    TARIMSAL_SULAMA_FATURALANAN = original_data$TARIMSAL_SULAMA_FATURALANAN,
    AYDINLATMA_FATURALANAN = original_data$AYDINLATMA_FATURALANAN,
    MESKEN_VERTICAL = numeric(n_rows),
    SANAYI_VERTICAL = numeric(n_rows),
    TICARETHANE_VERTICAL = numeric(n_rows),
    TARIMSAL_SULAMA_VERTICAL = numeric(n_rows),
    AYDINLATMA_VERTICAL = numeric(n_rows),
    MESKEN_HORIZONTAL = numeric(n_rows),
    SANAYI_HORIZONTAL = numeric(n_rows),
    TICARETHANE_HORIZONTAL = numeric(n_rows),
    TARIMSAL_SULAMA_HORIZONTAL = numeric(n_rows),
    AYDINLATMA_HORIZONTAL = numeric(n_rows)
  )
  
  # Calculate the vertical values
  for(t in 2:n_rows) {
    # MESKEN_VERTICAL
    vertical_data$MESKEN_VERTICAL[t] <- vertical_data$MESKEN_FATURALANAN[t] - 
      ((vertical_data$MESKEN_FATURALANAN[t-1] / original_data$MESKEN_ABONE_SAYISI[t-1]) * 
         original_data$MESKEN_ABONE_SAYISI[t])
    
    vertical_data$MESKEN_HORIZONTAL[t] <- (vertical_data$MESKEN_FATURALANAN[t] - vertical_data$MESKEN_FATURALANAN[t-1]) - vertical_data$MESKEN_VERTICAL[t]

    # SANAYI_VERTICAL
    vertical_data$SANAYI_VERTICAL[t] <- vertical_data$SANAYI_FATURALANAN[t] - 
      ((vertical_data$SANAYI_FATURALANAN[t-1] / original_data$SANAYI_ABONE_SAYISI[t-1]) * 
         original_data$SANAYI_ABONE_SAYISI[t])
    
    
    vertical_data$SANAYI_HORIZONTAL[t] <- (vertical_data$SANAYI_FATURALANAN[t] - vertical_data$SANAYI_FATURALANAN[t-1]) - vertical_data$SANAYI_VERTICAL[t]
    
    
    # TICARETHANE_VERTICAL
    vertical_data$TICARETHANE_VERTICAL[t] <- vertical_data$TICARETHANE_FATURALANAN[t] - 
      ((vertical_data$TICARETHANE_FATURALANAN[t-1] / original_data$TICARETHANE_ABONE_SAYISI[t-1]) * 
         original_data$TICARETHANE_ABONE_SAYISI[t])
    
    
    vertical_data$TICARETHANE_HORIZONTAL[t] <- (vertical_data$TICARETHANE_FATURALANAN[t] - vertical_data$TICARETHANE_FATURALANAN[t-1]) - vertical_data$TICARETHANE_VERTICAL[t]
    
    
    # TARIMSAL_SULAMA_VERTICAL
    vertical_data$TARIMSAL_SULAMA_VERTICAL[t] <- vertical_data$TARIMSAL_SULAMA_FATURALANAN[t] - 
      ((vertical_data$TARIMSAL_SULAMA_FATURALANAN[t-1] / original_data$TARIMSAL_SULAMA_ABONE_SAYISI[t-1]) * 
         original_data$TARIMSAL_SULAMA_ABONE_SAYISI[t])
    
    
    vertical_data$TARIMSAL_SULAMA_HORIZONTAL[t] <- (vertical_data$TARIMSAL_SULAMA_FATURALANAN[t] - vertical_data$TARIMSAL_SULAMA_FATURALANAN[t-1]) - vertical_data$TARIMSAL_SULAMA_VERTICAL[t]
    
    
    
    # AYDINLATMA_VERTICAL
    vertical_data$AYDINLATMA_VERTICAL[t] <- vertical_data$AYDINLATMA_FATURALANAN[t] - 
      ((vertical_data$AYDINLATMA_FATURALANAN[t-1] / original_data$AYDINLATMA_ABONE_SAYISI[t-1]) * 
         original_data$AYDINLATMA_ABONE_SAYISI[t])
    
    
    vertical_data$AYDINLATMA_HORIZONTAL[t] <- (vertical_data$AYDINLATMA_FATURALANAN[t] - vertical_data$AYDINLATMA_FATURALANAN[t-1]) - vertical_data$AYDINLATMA_VERTICAL[t]
    
    
  }
  
  # For the first year, set vertical values to NA (since we can't calculate t-1)
  vertical_data$MESKEN_VERTICAL[1] <- NA
  vertical_data$SANAYI_VERTICAL[1] <- NA
  vertical_data$TICARETHANE_VERTICAL[1] <- NA
  vertical_data$TARIMSAL_SULAMA_VERTICAL[1] <- NA
  vertical_data$AYDINLATMA_VERTICAL[1] <- NA
  
  
  vertical_data$MESKEN_HORIZONTAL[1] <- NA
  vertical_data$SANAYI_HORIZONTAL[1] <- NA
  vertical_data$TICARETHANE_HORIZONTAL[1] <- NA
  vertical_data$TARIMSAL_SULAMA_HORIZONTAL[1] <- NA
  vertical_data$AYDINLATMA_HORIZONTAL[1] <- NA
  
  
  vertical_data <- vertical_data[2:nrow(vertical_data),]
  
  # Write the data to the sheet
  writeData(vertical_workbook, 
            sheet = output_sheet_name, 
            x = vertical_data, 
            startCol = 1, 
            startRow = 1, 
            colNames = TRUE, 
            rowNames = FALSE)
  
  # Apply the style
  addStyle(vertical_workbook, 
           sheet = output_sheet_name, 
           style = my_style, 
           rows = 1:(n_rows + 1), 
           cols = 1:12, 
           gridExpand = TRUE)
  
  unlink(paste0(user_root_path,"/",
                config$Ana_Klasör_Yolu, "/",
                config$İl, "/",
                config$İlçe, "/",
                config$proje_ismi, "/",
                "sonuclar/SLF Sonuçları/5.Yük Tahmini/girdi"), recursive = TRUE)
  dir.create(paste0(user_root_path,"/",
                    config$Ana_Klasör_Yolu, "/",
                    config$İl, "/",
                    config$İlçe, "/",
                    config$proje_ismi, "/",
                    "sonuclar/SLF Sonuçları/5.Yük Tahmini/girdi"), recursive = TRUE)
  
  
  print("Oluşturulan rakamlar ilgili dosyaya yazılıyor...")
  
  # Save the new workbook to the same directory as the input file
  saveWorkbook(vertical_workbook,
               file = paste0(user_root_path,"/",
                             config$Ana_Klasör_Yolu, "/",
                             config$İl, "/",
                             config$İlçe, "/",
                             config$proje_ismi, "/",
                             config$ELF$hor_ver_dosyası),
               overwrite = TRUE)
}


# Call the function to create the vertical analysis file for the specified sheet
create_vertical_analysis_file(sheet_index)



